---
- name: Update APT package index
  hosts: all
  become: yes  # Run tasks as root
  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Update the cache if it's older than 1 hour
