---
- name: Update and upgrade apt packages
  hosts: all
  user: ansible
  become: true

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true
