---
- hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Upgrade all packages
      apt:
        upgrade: safe
        
    - name: Clean up unused packages
      apt:
        autoremove: yes    
